USE ivy;

CREATE TABLE ivy.tipos_logradouro (
	cod_tipo_logradouro INT auto_increment NOT NULL,
	descricao VARCHAR(50) NOT NULL,
	abreviacao varchar(10) NULL,

	CONSTRAINT tipos_logradouro_PK PRIMARY KEY (cod_tipo_logradouro)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;

INSERT INTO 
	tipos_logradouro (descricao)
VALUES
	('Área'),
	('Acesso'),
	('Acampamento'),
	('Acesso Local'),
	('Adro'),
	('Área Especial'),
	('Aeroporto'),
	('Alameda'),
	('Avenida Marginal Direita'),
	('Avenida Marginal Esquerda'),
	('Anel Viário'),
	('Antiga Estrada'),
	('Artéria'),
	('Alto'),
	('Atalho'),
	('Área Verde'),
	('Avenida'),
	('Avenida Contorno'),
	('Avenida Marginal'),
	('Avenida Velha'),
	('Balneário'),
	('Beco'),
	('Buraco'),
	('Belvedere'),
	('Bloco'),
	('Balão'),
	('Blocos'),
	('Bulevar'),
	('Bosque'),
	('Boulevard'),
	('Baixa'),
	('Cais'),
	('Calçada'),
	('Caminho'),
	('Canal'),
	('Chácara'),
	('Chapadão'),
	('Ciclovia'),
	('Circular'),
	('Conjunto'),
	('Conjunto Mutirão'),
	('Complexo Viário'),
	('Colônia'),
	('Comunidade'),
	('Condomínio'),
	('Corredor'),
	('Campo'),
	('Córrego'),
	('Contorno'),
	('Descida'),
	('Desvio'),
	('Distrito'),
	('Entre Bloco'),
	('Estrada Intermunicipal'),
	('Enseada'),
	('Entrada Particular'),
	('Entre Quadra'),
	('Escada'),
	('Escadaria'),
	('Estrada Estadual'),
	('Estrada Vicinal'),
	('Estrada de Ligação'),
	('Estrada Municipal'),
	('Esplanada'),
	('Estrada de Servidão'),
	('Estrada'),
	('Estrada Velha'),
	('Estrada Antiga'),
	('Estação'),
	('Estádio'),
	('Estância'),
	('Estrada Particular'),
	('Estacionamento'),
	('Evangélica'),
	('Elevada'),
	('Eixo Industrial'),
	('Favela'),
	('Fazenda'),
	('Ferrovia'),
	('Fonte'),
	('Feira'),
	('Forte'),
	('Galeria'),
	('Granja'),
	('Núcleo Habitacional'),
	('Ilha'),
	('Indeterminado'),
	('Ilhota'),
	('Jardim'),
	('Jardinete'),
	('Ladeira'),
	('Lagoa'),
	('Lago'),
	('Loteamento'),
	('Largo'),
	('Lote'),
	('Mercado'),
	('Marina'),
	('Modulo'),
	('Projeção'),
	('Morro'),
	('Monte'),
	('Núcleo'),
	('Núcleo Rural'),
	('Outeiro'),
	('Paralela'),
	('Passeio'),
	('Pátio'),
	('Praça'),
	('Praça de Esportes'),
	('Parada'),
	('Paradouro'),
	('Ponta'),
	('Praia'),
	('Prolongamento'),
	('Parque Municipal'),
	('Parque'),
	('Parque Residencial'),
	('Passarela'),
	('Passagem'),
	('Passagem de Pedestre'),
	('Passagem Subterrânea'),
	('Ponte'),
	('Porto'),
	('Quadra'),
	('Quinta'),
	('Quintas'),
	('Rua'),
	('Rua Integração'),
	('Rua de Ligação'),
	('Rua Particular'),
	('Rua Velha'),
	('Ramal'),
	('Recreio'),
	('Recanto'),
	('Retiro'),
	('Residencial'),
	('Reta'),
	('Ruela'),
	('Rampa'),
	('Rodo Anel'),
	('Rodovia'),
	('Rotula'),
	('Rua de Pedestre'),
	('Margem'),
	('Retorno'),
	('Rotatória'),
	('Segunda Avenida'),
	('Sitio'),
	('Servidão'),
	('Setor'),
	('Subida'),
	('Trincheira'),
	('Terminal'),
	('Trecho'),
	('Trevo'),
	('Túnel'),
	('Travessa'),
	('Travessa Particular'),
	('Travessa Velha'),
	('Unidade'),
	('Via'),
	('Via Coletora'),
	('Via Local'),
	('Via de Acesso'),
	('Vala'),
	('Via Costeira'),
	('Viaduto'),
	('Via Expressa'),
	('Vereda'),
	('Via Elevado'),
	('Vila'),
	('Viela'),
	('Vale'),
	('Via Litorânea'),
	('Via de Pedestre'),
	('Variante');